// <auto-generated />
using System;
using System.Collections.Generic;
using Lazerboard.Data.Database;
using Lazerboard.Data.Database.Entities.Enums;
using Lazerboard.Data.OsuEntities.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OsuScoreStats.Migrations
{
    [DbContext(typeof(ScoreDataContext))]
    [Migration("20260917110727_AddLastScannedAtColumn")]
    partial class AddLastScannedAtColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "beatmap_status", new[] { "approved", "graveyard", "loved", "pending", "qualified", "ranked", "wip" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "grade", new[] { "a", "b", "c", "d", "f", "s", "sh", "x", "xh" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mode", new[] { "fruits", "mania", "osu", "taiko" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "scan_event_type", new[] { "main_seeding_finished", "main_seeding_started", "rescan_finished", "rescan_started", "secondary_seeding_finished", "secondary_seeding_started", "user_scan_finished", "user_scan_started" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "score_source", new[] { "leaderboard_scan", "score_fetcher" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("ApproachRate")
                        .HasColumnType("real")
                        .HasColumnName("approach_rate");

                    b.Property<float?>("BPM")
                        .HasColumnType("real")
                        .HasColumnName("bpm");

                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmapset_id");

                    b.Property<float>("CircleSize")
                        .HasColumnType("real")
                        .HasColumnName("circle_size");

                    b.Property<float>("Difficulty")
                        .HasColumnType("real")
                        .HasColumnName("difficulty");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty_name");

                    b.Property<int>("DrainLength")
                        .HasColumnType("integer")
                        .HasColumnName("drain_length");

                    b.Property<float?>("Health")
                        .HasColumnType("real")
                        .HasColumnName("health");

                    b.Property<Mode>("Mode")
                        .HasColumnType("mode")
                        .HasColumnName("mode");

                    b.Property<float>("OverallDifficulty")
                        .HasColumnType("real")
                        .HasColumnName("overall_difficulty");

                    b.Property<BeatmapStatus>("Status")
                        .HasColumnType("beatmap_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_beatmaps");

                    b.HasIndex("BeatmapsetId")
                        .HasDatabaseName("ix_beatmaps_beatmapset_id");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_beatmaps_difficulty");

                    b.HasIndex("Mode")
                        .HasDatabaseName("ix_beatmaps_mode");

                    b.ToTable("beatmaps", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmapset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<DateTimeOffset?>("FinishedScanningAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_scanning_at");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_explicit");

                    b.Property<DateTimeOffset?>("MainFinishedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("main_finished_processing_at");

                    b.Property<DateTimeOffset?>("MainStartedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("main_started_processing_at");

                    b.Property<DateTimeOffset?>("RankedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ranked_date");

                    b.Property<DateTimeOffset?>("SecondaryFinishedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("secondary_finished_processing_at");

                    b.Property<DateTimeOffset?>("SecondaryStartedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("secondary_started_processing_at");

                    b.Property<DateTimeOffset?>("StartedScanningAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_scanning_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_beatmapsets");

                    b.HasIndex("FinishedScanningAt")
                        .HasDatabaseName("ix_beatmapsets_finished_scanning_at");

                    b.HasIndex("MainStartedProcessingAt")
                        .HasDatabaseName("ix_beatmapsets_main_started_processing_at");

                    b.HasIndex("RankedDate")
                        .HasDatabaseName("ix_beatmapsets_ranked_date");

                    b.HasIndex("SecondaryFinishedProcessingAt")
                        .HasDatabaseName("ix_beatmapsets_secondary_finished_processing_at");

                    b.HasIndex("SecondaryStartedProcessingAt")
                        .HasDatabaseName("ix_beatmapsets_secondary_started_processing_at");

                    b.HasIndex("StartedScanningAt")
                        .HasDatabaseName("ix_beatmapsets_started_scanning_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_beatmapsets_user_id");

                    b.ToTable("beatmapsets", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.BeatmapsetScanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ScanEventType>("EventType")
                        .HasColumnType("scan_event_type")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.HasKey("Id")
                        .HasName("pk_beatmapset_scan_logs");

                    b.ToTable("beatmapset_scan_logs", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.RemovedBeatmapset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_date");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<DateTimeOffset?>("RankedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ranked_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_removed_beatmapsets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_removed_beatmapsets_user_id");

                    b.ToTable("removed_beatmapsets", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Score", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<float>("Accuracy")
                        .HasColumnType("real")
                        .HasColumnName("accuracy");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_id");

                    b.Property<long>("ClassicTotalScore")
                        .HasColumnType("bigint")
                        .HasColumnName("classic_total_score");

                    b.Property<int>("Combo")
                        .HasColumnType("integer")
                        .HasColumnName("combo");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Grade>("Grade")
                        .HasColumnType("grade")
                        .HasColumnName("grade");

                    b.Property<bool?>("IsConvert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_convert");

                    b.Property<bool?>("IsLazerScore")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lazer_score");

                    b.Property<bool?>("IsPerfectCombo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_perfect_combo");

                    b.Property<int?>("LegacyTotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_total_score");

                    b.Property<int?>("Misses")
                        .HasColumnType("integer")
                        .HasColumnName("misses");

                    b.PrimitiveCollection<List<string>>("ModAcronyms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mod_acronyms");

                    b.Property<Mode>("Mode")
                        .HasColumnType("mode")
                        .HasColumnName("mode");

                    b.Property<float?>("PP")
                        .HasColumnType("real")
                        .HasColumnName("pp");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<ScoreSource>("ScoreSource")
                        .HasColumnType("score_source")
                        .HasColumnName("score_source");

                    b.Property<double?>("SpeedChange")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_change");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Statistics", "Lazerboard.Data.Database.Entities.Score.Statistics#Statistics", b1 =>
                        {
                            b1.Property<int?>("CountGood");

                            b1.Property<int?>("CountGreat");

                            b1.Property<int?>("CountMeh");

                            b1.Property<int?>("CountMiss");

                            b1.Property<int?>("CountOk");

                            b1.Property<int?>("CountPerfect");

                            b1.Property<int?>("LegacySliderEndMisses");

                            b1.Property<int?>("LegacySliderEnds");

                            b1.Property<int?>("SliderEnds");

                            b1.Property<int?>("SliderTickMisses");

                            b1.Property<int?>("SliderTicks");

                            b1.Property<int?>("SpinnerBonus");

                            b1.Property<int?>("SpinnerSpins");

                            b1.ToJson("statistics");
                        });

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex("ModAcronyms")
                        .HasDatabaseName("ix_scores_mod_acronyms");

                    b.HasIndex("ScoreSource")
                        .HasDatabaseName("ix_scores_score_source");

                    b.HasIndex("Date", "Mode")
                        .HasDatabaseName("ix_scores_date_mode");

                    b.HasIndex("Rank", "Mode")
                        .HasDatabaseName("ix_scores_rank_mode");

                    b.HasIndex("TotalScore", "Mode")
                        .HasDatabaseName("ix_scores_total_score_mode");

                    b.HasIndex("UserId", "Date", "Mode")
                        .HasDatabaseName("ix_scores_user_id_date_mode");

                    b.HasIndex("BeatmapId", "Mode", "TotalScore", "Date")
                        .HasDatabaseName("ix_scores_beatmap_id_mode_total_score_date");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.UnlistedScore", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<float>("Accuracy")
                        .HasColumnType("real")
                        .HasColumnName("accuracy");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_id");

                    b.Property<long>("ClassicTotalScore")
                        .HasColumnType("bigint")
                        .HasColumnName("classic_total_score");

                    b.Property<int>("Combo")
                        .HasColumnType("integer")
                        .HasColumnName("combo");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Grade>("Grade")
                        .HasColumnType("grade")
                        .HasColumnName("grade");

                    b.Property<bool?>("IsConvert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_convert");

                    b.Property<bool?>("IsLazerScore")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lazer_score");

                    b.Property<bool?>("IsPerfectCombo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_perfect_combo");

                    b.Property<int?>("LegacyTotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_total_score");

                    b.Property<int?>("Misses")
                        .HasColumnType("integer")
                        .HasColumnName("misses");

                    b.PrimitiveCollection<List<string>>("ModAcronyms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mod_acronyms");

                    b.Property<Mode>("Mode")
                        .HasColumnType("mode")
                        .HasColumnName("mode");

                    b.Property<float?>("PP")
                        .HasColumnType("real")
                        .HasColumnName("pp");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<ScoreSource>("ScoreSource")
                        .HasColumnType("score_source")
                        .HasColumnName("score_source");

                    b.Property<double?>("SpeedChange")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_change");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Statistics", "Lazerboard.Data.Database.Entities.UnlistedScore.Statistics#Statistics", b1 =>
                        {
                            b1.Property<int?>("CountGood");

                            b1.Property<int?>("CountGreat");

                            b1.Property<int?>("CountMeh");

                            b1.Property<int?>("CountMiss");

                            b1.Property<int?>("CountOk");

                            b1.Property<int?>("CountPerfect");

                            b1.Property<int?>("LegacySliderEndMisses");

                            b1.Property<int?>("LegacySliderEnds");

                            b1.Property<int?>("SliderEnds");

                            b1.Property<int?>("SliderTickMisses");

                            b1.Property<int?>("SliderTicks");

                            b1.Property<int?>("SpinnerBonus");

                            b1.Property<int?>("SpinnerSpins");

                            b1.ToJson("statistics");
                        });

                    b.HasKey("Id")
                        .HasName("pk_unlisted_scores");

                    b.HasIndex("BeatmapId")
                        .HasDatabaseName("ix_unlisted_scores_beatmap_id");

                    b.HasIndex("ScoreSource")
                        .HasDatabaseName("ix_unlisted_scores_score_source");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_unlisted_scores_user_id");

                    b.ToTable("unlisted_scores", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_restricted");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_users_country_code");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.UserScanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ScanEventType>("EventType")
                        .HasColumnType("scan_event_type")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.HasKey("Id")
                        .HasName("pk_user_scan_logs");

                    b.ToTable("user_scan_logs", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmap", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Beatmapset", "Beatmapset")
                        .WithMany("Beatmaps")
                        .HasForeignKey("BeatmapsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beatmaps_beatmapsets_beatmapset_id");

                    b.Navigation("Beatmapset");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmapset", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_beatmapsets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.RemovedBeatmapset", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_removed_beatmapsets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Score", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Beatmap", "Beatmap")
                        .WithMany("Scores")
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_beatmaps_beatmap_id");

                    b.HasOne("Lazerboard.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_users_user_id");

                    b.Navigation("Beatmap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.UnlistedScore", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Beatmap", "Beatmap")
                        .WithMany()
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unlisted_scores_beatmaps_beatmap_id");

                    b.HasOne("Lazerboard.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unlisted_scores_users_user_id");

                    b.Navigation("Beatmap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.User", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("fk_users_countries_country_code");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmap", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmapset", b =>
                {
                    b.Navigation("Beatmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
