// <auto-generated />
using System;
using System.Collections.Generic;
using Lazerboard.Data.Database;
using Lazerboard.Data.Database.Entities.Enums;
using Lazerboard.Data.OsuEntities.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OsuScoreStats.Migrations
{
    [DbContext(typeof(ScoreDataContext))]
    partial class ScoreDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "beatmap_status", new[] { "approved", "graveyard", "loved", "pending", "qualified", "ranked", "wip" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "grade", new[] { "a", "b", "c", "d", "f", "s", "sh", "x", "xh" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mode", new[] { "fruits", "mania", "osu", "taiko" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "score_source", new[] { "leaderboard_scan", "score_fetcher" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("ApproachRate")
                        .HasColumnType("real")
                        .HasColumnName("approach_rate");

                    b.Property<float?>("BPM")
                        .HasColumnType("real")
                        .HasColumnName("bpm");

                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmapset_id");

                    b.Property<float>("CircleSize")
                        .HasColumnType("real")
                        .HasColumnName("circle_size");

                    b.Property<float>("Difficulty")
                        .HasColumnType("real")
                        .HasColumnName("difficulty");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty_name");

                    b.Property<int>("DrainLength")
                        .HasColumnType("integer")
                        .HasColumnName("drain_length");

                    b.Property<float?>("Health")
                        .HasColumnType("real")
                        .HasColumnName("health");

                    b.Property<Mode>("Mode")
                        .HasColumnType("mode")
                        .HasColumnName("mode");

                    b.Property<float>("OverallDifficulty")
                        .HasColumnType("real")
                        .HasColumnName("overall_difficulty");

                    b.Property<BeatmapStatus>("Status")
                        .HasColumnType("beatmap_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_beatmaps");

                    b.HasIndex("BeatmapsetId")
                        .HasDatabaseName("ix_beatmaps_beatmapset_id");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_beatmaps_difficulty");

                    b.ToTable("beatmaps", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmapset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_beatmapsets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_beatmapsets_user_id");

                    b.ToTable("beatmapsets", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Score", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<float>("Accuracy")
                        .HasColumnType("real")
                        .HasColumnName("accuracy");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_id");

                    b.Property<long>("ClassicTotalScore")
                        .HasColumnType("bigint")
                        .HasColumnName("classic_total_score");

                    b.Property<int>("Combo")
                        .HasColumnType("integer")
                        .HasColumnName("combo");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Grade>("Grade")
                        .HasColumnType("grade")
                        .HasColumnName("grade");

                    b.Property<int?>("LegacyTotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_total_score");

                    b.Property<int?>("Misses")
                        .HasColumnType("integer")
                        .HasColumnName("misses");

                    b.PrimitiveCollection<List<string>>("ModAcronyms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mod_acronyms");

                    b.Property<Mode>("Mode")
                        .HasColumnType("mode")
                        .HasColumnName("mode");

                    b.Property<float?>("PP")
                        .HasColumnType("real")
                        .HasColumnName("pp");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<ScoreSource>("ScoreSource")
                        .HasColumnType("score_source")
                        .HasColumnName("score_source");

                    b.Property<double?>("SpeedChange")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_change");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex("BeatmapId")
                        .HasDatabaseName("ix_scores_beatmap_id");

                    b.HasIndex("ModAcronyms")
                        .HasDatabaseName("ix_scores_mod_acronyms");

                    b.HasIndex("Date", "Mode")
                        .HasDatabaseName("ix_scores_date_mode");

                    b.HasIndex("Rank", "Mode")
                        .HasDatabaseName("ix_scores_rank_mode");

                    b.HasIndex("TotalScore", "Mode")
                        .HasDatabaseName("ix_scores_total_score_mode");

                    b.HasIndex("UserId", "Date", "Mode")
                        .HasDatabaseName("ix_scores_user_id_date_mode");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.ScorePendingDeletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at");

                    b.Property<decimal>("ScoreId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("score_id");

                    b.HasKey("Id")
                        .HasName("pk_scores_pending_deletion");

                    b.HasIndex("MarkedAt")
                        .HasDatabaseName("ix_scores_pending_deletion_marked_at");

                    b.HasIndex("ScoreId")
                        .IsUnique()
                        .HasDatabaseName("ix_scores_pending_deletion_score_id");

                    b.ToTable("scores_pending_deletion", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_users_country_code");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmap", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Beatmapset", "Beatmapset")
                        .WithMany()
                        .HasForeignKey("BeatmapsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beatmaps_beatmapsets_beatmapset_id");

                    b.Navigation("Beatmapset");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Beatmapset", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_beatmapsets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.Score", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Beatmap", "Beatmap")
                        .WithMany()
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_beatmaps_beatmap_id");

                    b.HasOne("Lazerboard.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_users_user_id");

                    b.Navigation("Beatmap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.ScorePendingDeletion", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Score", "Score")
                        .WithOne()
                        .HasForeignKey("Lazerboard.Data.Database.Entities.ScorePendingDeletion", "ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_pending_deletion_scores_score_id");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Lazerboard.Data.Database.Entities.User", b =>
                {
                    b.HasOne("Lazerboard.Data.Database.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("fk_users_countries_country_code");

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
