networks:
  main:

services:
  init:
    image: alpine:latest
    user: root
    volumes:
      - ./BeatmapCache:/app/BeatmapCache
      - ./logs:/app/logs
      - ./keys:/app/keys
    command: |
      sh -c "mkdir -p /app/BeatmapCache /app/logs/scorefetcher /app/logs/backend /app/logs/discordhooks /app/keys &&
             chown -R ${UID:-1000}:${GID:-1000} /app/BeatmapCache /app/logs /app/keys"
    restart: "no"
  
  migrations:
    image: ghcr.io/n-saraseka/lazerboard-migrations:latest
    depends_on:
      "db":
        condition: service_healthy
      "init":
        condition: service_completed_successfully
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    restart: on-failure:1
    networks:
      - main
  
  scorefetcher:
    image: ghcr.io/n-saraseka/lazerboard-scorefetcher:latest
    depends_on:
      "migrations":
        condition: service_completed_successfully
      "init":
        condition: service_completed_successfully
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      .env
    environment:
      - ASPNETCORE_URLS=http://+:8081
    volumes:
      - ./logs/scorefetcher:/app/Logs
      - ./BeatmapCache:/app/BeatmapCache
    restart: unless-stopped
    networks:
      - main
  
  discordhooks:
    image: ghcr.io/n-saraseka/lazerboard-discordhooks:latest
    depends_on:
      "migrations":
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./logs/discordhooks:/app/Logs
    restart: unless-stopped
    networks:
      - main
  
  backend:
    image: ghcr.io/n-saraseka/lazerboard-backend:latest
    depends_on:
      "migrations":
        condition: service_completed_successfully
      "init":
        condition: service_completed_successfully
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      .env
    volumes:
      - ./logs/backend:/app/Logs
      - ./keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
    networks:
      - main
  
  frontend:
    image: ghcr.io/n-saraseka/lazerboard-frontend:latest
    depends_on:
      "backend":
        condition: service_started
    volumes:
      - ./Caddy/data:/data
      - ./Caddy/config:/config
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - main
  
  redis:
    image: redis:8-alpine
    env_file:
      - .env
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: |
      sh -c "
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      "
    networks:
      - main
  
  db:
    image: postgres:18-alpine
    env_file:
      .env
    volumes:
      - ./db:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main