networks:
  main:

services:
  backend:
    build: ./Backend
    depends_on:
      "db":
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=http://*:5000
      - Database__Database=lazerleaderboards
      - Database__Host=db
      - Database__Port=5432
      - Database__Username=postgres
      - Database__Password=postgres
      - OsuApi__ClientId
      - OsuApi__ClientSecret
      - UseFirehose=false
      - EnableDatabaseSeeding=false
    volumes:
      - ./logs/backend:/app/Logs
      - ./BeatmapCache:/app/BeatmapCache
      - ./keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
    networks:
      - main
  
  frontend:
    build: 
      context: ./Frontend
      dockerfile: dev.Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - main
  
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lazerleaderboards
      - POSTGRES_HOST=localhost
      - PGDATA=/data/postgres
    volumes:
      - ./db:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main