networks:
  main:

services:
  init:
    image: alpine:latest
    user: root
    volumes:
      - ./BeatmapCache:/app/BeatmapCache
      - ./logs:/app/logs
      - ./keys:/app/keys
    command: |
      sh -c "mkdir -p /app/BeatmapCache /app/logs/scorefetcher /app/logs/backend /app/keys &&
             chown -R ${UID:-1000}:${GID:-1000} /app/BeatmapCache /app/logs /app/keys"
    restart: "no"
  
  migrations:
    image: ghcr.io/n-saraseka/lazerboard-migrations:latest
    depends_on:
      "db":
        condition: service_healthy
      "init":
        condition: service_completed_successfully
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - prod.env
    restart: on-failure:1
    networks:
      - main
  
  scorefetcher:
    image: ghcr.io/n-saraseka/lazerboard-scorefetcher:latest
    depends_on:
      "migrations":
        condition: service_completed_successfully
      "init":
        condition: service_completed_successfully
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      prod.env
    environment:
      - ASPNETCORE_URLS=http://+:8081
    volumes:
      - ./logs/scorefetcher:/app/Logs
      - ./BeatmapCache:/app/BeatmapCache
    restart: unless-stopped
    networks:
      - main
  
  discordhooks:
    image: ghcr.io/n-saraseka/lazerboard-discordhooks:latest
    depends_on:
      "migrations":
        condition: service_completed_successfully
    env_file:
      - dev.env
    volumes:
      - ./logs/discordhooks:/app/Logs
    restart: unless-stopped
    networks:
      - main
  
  backend:
    image: ghcr.io/n-saraseka/lazerboard-backend:latest
    depends_on:
      "migrations":
        condition: service_completed_successfully
      "init":
        condition: service_completed_successfully
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      prod.env
    volumes:
      - ./logs/backend:/app/Logs
      - ./keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
    networks:
      - main
  
  frontend:
    image: ghcr.io/n-saraseka/lazerboard-frontend:latest
    depends_on:
      "backend":
        condition: service_started
    volumes:
      - ./Caddy/data:/data
      - ./Caddy/config:/config
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - main
      
  db:
    image: postgres:18-alpine
    env_file:
      prod.env
    volumes:
      - ./db:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main