networks:
  main:

services:
  migrations:
    build:
      context: ./Backend
      dockerfile: ./Lazerboard.Data/Dockerfile
    depends_on:
      "db":
        condition: service_healthy
    env_file:
      - dev.env
    restart: on-failure:1
    networks:
      - main

  scorefetcher:
    build:
      context: ./Backend
      dockerfile: ./Lazerboard.ScoreFetcher/Dockerfile
    depends_on:
      "migrations":
        condition: service_completed_successfully
    env_file:
      - dev.env
    environment:
      - ASPNETCORE_URLS=http://+:8081
    volumes:
      - ./logs/scorefetcher:/app/Logs
      - ./BeatmapCache:/app/BeatmapCache
    restart: unless-stopped
    networks:
      - main
  
  discordhooks:
    build:
      context: ./Backend
      dockerfile: ./Lazerboard.DiscordHooks/Dockerfile
    depends_on:
      "migrations":
        condition: service_completed_successfully
    env_file:
      - dev.env
    volumes:
      - ./logs/discordhooks:/app/Logs
    restart: unless-stopped
    networks:
      - main

  backend:
    build:
      context: ./Backend
      dockerfile: ./Lazerboard/Dockerfile
    depends_on:
      "migrations":
        condition: service_completed_successfully
    env_file:
      - dev.env
    volumes:
      - ./logs/backend:/app/Logs
      - ./keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
    networks:
      - main
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: dev.Dockerfile
    depends_on:
      "backend":
        condition: service_started
    volumes:
      - ./Caddy/data:/data
      - ./Caddy/config:/config
      - ./Caddy/dev.Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - main
  
  db:
    image: postgres:18-alpine
    env_file:
      - dev.env
    volumes:
      - ./db:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main