name: Create .env file
author: SomeMelGuy
description: Create .env file from secrets
runs:
  using: composite
  steps:
    - name: Create .env
      shell: bash
      run: |
        touch ./.env
        echo "POSTGRES_USER=${{ secrets.PSQL_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.PSQL_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.PSQL_DB }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.PSQL_HOST }}" >> .env
        echo "POSTGRES_PORT=${{ secrets.PSQL_PORT }}" >> .env
        echo "PGDATA=/data/postgres" >> .env
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
        echo "REDIS_USER=${{ secrets.REDIS_USER }}" >> .env
        echo "REDIS_USER_PASSWORD=${{ secrets.REDIS_USER_PASSWORD }}" >> .env
        echo "ASPNETCORE_ENVIRONMENT=Production" >> .env
        echo "Database__Database=${{ secrets.PSQL_DB }}" >> .env
        echo "Database__Host=db" >> .env
        echo "Database__Port=${{ secrets.PSQL_PORT }}" >> .env
        echo "Database__Username=${{ secrets.PSQL_USER }}" >> .env
        echo "Database__Password=${{ secrets.PSQL_PASSWORD }}" >> .env
        echo "Redis__Host=redis" >> .env
        echo "Redis__Username=${{ secrets.REDIS_USER }}" >> .env
        echo "Redis__Password=${{ secrets.REDIS_USER_PASSWORD }}" >> .env
        echo "ExternalApis__Host=externalapis" >> .env
        echo "ExternalApis__Port=8080" >> .env
        echo "ExternalApis__OsuApi__ClientId=${{ secrets.OSUAPI_CLIENTID }}" >> .env
        echo "ExternalApis__OsuApi__ClientSecret=${{ secrets.OSUAPI_CLIENTSECRET }}" >> .env
        echo "Caching__FileTTL=120" >> .env
        echo "ScoreCountUpdateIntervalMinutes=15" >> .env
        echo "EnableDatabaseSeeding=true" >> .env
        echo "RestartPolicy__LeaderboardScanCatchUp=true" >> .env
        echo "RestartPolicy__FirehoseCatchUp=true" >> .env
        echo "DiscordHooks__BeatmapScores__HookURL=${{ secrets.HOOKS_SCANHOOKURL }}" >> .env
        echo "DiscordHooks__BeatmapScores__Enabled=true" >> .env
        echo "DiscordHooks__BeatmapScores__UpdateIntervalMinutes=30" >> .env
        echo "DeleteScoresAfter=4" >> .env
        scp ./.env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/.env
        