name: Create .env file
author: SomeMelGuy
description: Create .env file from secrets
inputs:
  psql_user:
    description: 'PostgreSQL user'
    required: true
  psql_password:
    description: 'PostgreSQL password'
    required: true
  psql_db:
    description: 'PostgreSQL database name'
    required: true
  psql_host:
    description: 'PostgreSQL host address'
    required: true
  psql_port:
    description: 'PostgreSQL port'
    required: true
  redis_password:
    description: 'Redis password'
    required: true
  redis_user:
    description: 'Redis user'
    required: true
  redis_user_password:
    description: 'Redis user password'
    required: true
  osuapi_clientid:
    description: 'osu! API client ID'
    required: true
  osuapi_clientsecret:
    description: 'osu! API client secret'
    required: true
  hooks_latestmapurl:
    description: 'Latest beatmapset discord hook URL'
    required: true
  hooks_rescansurl:
    description: 'Beatmapset rescans discord hook URL'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_host:
    description: 'SSH host address'
    required: true
  work_dir:
    description: 'The work directory'
    required: true
runs:
  using: composite
  steps:
    - name: Create .env
      shell: bash
      run: |
        touch ./.env
        echo "POSTGRES_USER=${{ inputs.psql_user }}" >> .env
        echo "POSTGRES_PASSWORD=${{ inputs.psql_password }}" >> .env
        echo "POSTGRES_DB=${{ inputs.psql_db }}" >> .env
        echo "POSTGRES_HOST=${{ inputs.psql_host }}" >> .env
        echo "POSTGRES_PORT=${{ inputs.psql_port }}" >> .env
        echo "PGDATA=/data/postgres" >> .env
        echo "REDIS_PASSWORD=${{ inputs.redis_password }}" >> .env
        echo "REDIS_USER=${{ inputs.redis_user }}" >> .env
        echo "REDIS_USER_PASSWORD=${{ inputs.redis_user_password }}" >> .env
        echo "ASPNETCORE_ENVIRONMENT=Production" >> .env
        echo "Database__Database=${{ inputs.psql_db }}" >> .env
        echo "Database__Host=db" >> .env
        echo "Database__Port=${{ inputs.psql_port }}" >> .env
        echo "Database__Username=${{ inputs.psql_user }}" >> .env
        echo "Database__Password=${{ inputs.psql_password }}" >> .env
        echo "Redis__Host=redis" >> .env
        echo "Redis__Username=${{ inputs.redis_user }}" >> .env
        echo "Redis__Password=${{ inputs.redis_user_password }}" >> .env
        echo "ExternalApis__Host=externalapis" >> .env
        echo "ExternalApis__Port=8080" >> .env
        echo "ExternalApis__OsuApi__ClientId=${{ inputs.osuapi_clientid }}" >> .env
        echo "ExternalApis__OsuApi__ClientSecret=${{ inputs.osuapi_clientsecret }}" >> .env
        echo "Caching__FileTTL=120" >> .env
        echo "ScoreCountUpdateIntervalMinutes=15" >> .env
        echo "FetcherServices__MainSeeding=false" >> .env
        echo "FetcherServices__SecondarySeeding=true" >> .env
        echo "FetcherServices__Firehose=true" >> .env
        echo "FetcherServices__Rescans=true" >> .env
        echo "DiscordHooks__BeatmapScores__HookURL=${{ inputs.hooks_latestmapurl }}" >> .env
        echo "DiscordHooks__BeatmapScores__Enabled=true" >> .env
        echo "DiscordHooks__BeatmapScores__UpdateIntervalMinutes=30" >> .env
        echo "DiscordHooks__Scans__HookURL=${{ inputs.hooks_rescansurl }}" >> .env
        echo "DiscordHooks__Scans__Enabled=false" >> .env
        echo "DiscordHooks__Scans__UpdateIntervalMinutes=30" >> .env
        echo "DeleteScoresAfter=4" >> .env
        scp ./.env ${{ inputs.ssh_user }}@${{ inputs.ssh_host }}:${{ inputs.work_dir }}/.env
        