name: Cleanup post deploy
author: SomeMelGuy
description: Remove .env file and ssh
inputs:
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_host:
    description: 'SSH host address'
    required: true
  work_dir:
    description: 'The work directory'
    required: true
runs:
  using: composite
  steps:
    - name: Cleanup .env locally
      shell: bash
      run: rm -f ./.env
    - name: Cleanup .env from the server
      shell: bash
      run: |
        ssh ${{ inputs.ssh_user }}@${{ inputs.ssh_host }} "cd ${{ inputs.work_dir }} &&
        rm -f .env"
    - name: Cleanup ssh
      shell: bash
      run: rm -rf ~/.ssh