name: Build all images and deploy

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  MIGRATIONS_IMAGE_NAME: ${{ github.actor }}/lazerboard-migrations:latest
  SCOREFETCHER_IMAGE_NAME: ${{ github.actor }}/lazerboard-scorefetcher:latest
  BACKEND_IMAGE_NAME: ${{ github.actor }}/lazerboard-backend:latest
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/lazerboard-frontend:latest
  DISCORDHOOKS_IMAGE_NAME: ${{ github.actor }}/lazerboard-discordhooks:latest

jobs:
  publish-migrations:
    name: publish migrations image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish migrations
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard.Data/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}
  publish-scorefetcher:
    name: publish score fetcher image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish score fetcher
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard.ScoreFetcher/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.SCOREFETCHER_IMAGE_NAME }}
  publish-backend:
    name: publish backend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
  publish-frontend:
    name: publish frontend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish frontend
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        file: ./Frontend/production.Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
  publish-discordhooks:
    name: publish discord hooks image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Lazerboard.DiscordHooks/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DISCORDHOOKS_IMAGE_NAME }}
  deploy:
    needs:
      - publish-backend
      - publish-scorefetcher
      - publish-frontend
      - publish-migrations
      - publish-discordhooks
    name: deploy container
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: copy docker-compose to server
      run: |
        scp ./compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/compose.yaml
    - name: create .env file
      run: |
        touch ./.env
        echo "POSTGRES_USER=${{ secrets.PSQL_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.PSQL_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.PSQL_DB }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.PSQL_HOST }}" >> .env
        echo "POSTGRES_PORT=${{ secrets.PSQL_PORT }}" >> .env
        echo "PGDATA=/data/postgres" >> .env
        echo "ASPNETCORE_ENVIRONMENT=Production" >> .env
        echo "Database__Database=${{ secrets.PSQL_DB }}" >> .env
        echo "Database__Host=db" >> .env
        echo "Database__Port=${{ secrets.PSQL_PORT }}" >> .env
        echo "Database__Username=${{ secrets.PSQL_USER }}" >> .env
        echo "Database__Password=${{ secrets.PSQL_PASSWORD }}" >> .env
        echo "OsuApi__ClientId=${{ secrets.OSUAPI_CLIENTID }}" >> .env
        echo "OsuApi__ClientSecret=${{ secrets.OSUAPI_CLIENTSECRET }}" >> .env
        echo "DiscordHooks__BeatmapScores__HookURL=${{ secrets.HOOKS_SCANHOOKURL }}" >> .env
        echo "DiscordHooks__BeatmapScores__Enabled=true" >> .env
        echo "DiscordHooks__BeatmapScores__UpdateIntervalMinutes=30" >> .env
        echo "RestartPolicy__LeaderboardScanCatchUp=true" >> .env
        echo "RestartPolicy__FirehoseCatchUp=true" >> .env
        echo "Caching__FileTTL=120" >> .env
        echo "DeleteScoresAfter=4" >> .env
        echo "EnableDatabaseSeeding=true" >> .env
        scp ./.env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/.env
    - name: Unlock GPG key for pass
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
    - name: Login
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "echo '${{ secrets.PAT }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin"
    - name: deploy container
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} &&
        docker compose pull && UID=$(id -u) GID=$(id -g) docker compose up -d"
    - name: Logout
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker logout ghcr.io"
    - name: cleanup ssh
      if: always()
      run: rm -rf ~/.ssh
    - name: cleanup .env
      if: always()
      run: rm -f ./.env
