name: Build all images and deploy

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  MIGRATIONS_IMAGE_NAME: ${{ github.actor }}/lazerboard-migrations:latest
  SCOREFETCHER_IMAGE_NAME: ${{ github.actor }}/lazerboard-scorefetcher:latest
  BACKEND_IMAGE_NAME: ${{ github.actor }}/lazerboard-backend:latest
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/lazerboard-frontend:latest
  DISCORDHOOKS_IMAGE_NAME: ${{ github.actor }}/lazerboard-discordhooks:latest
  EXTERNALAPIS_IMAGE_NAME: ${{ github.actor }}/lazerboard-externalapis:latest

jobs:
  publish-migrations:
    name: publish migrations image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish migrations
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard.Data/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}
  publish-scorefetcher:
    name: publish score fetcher image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish score fetcher
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard.ScoreFetcher/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.SCOREFETCHER_IMAGE_NAME }}
  publish-backend:
    name: publish backend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
  publish-frontend:
    name: publish frontend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish frontend
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
  publish-discordhooks:
    name: publish discord hooks image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Lazerboard.DiscordHooks/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DISCORDHOOKS_IMAGE_NAME }}
  publish-externalapis:
    name: publish external apis image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Lazerboard.DiscordHooks/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.EXTERNALAPIS_IMAGE_NAME }}
    
  deploy:
    needs:
      - publish-backend
      - publish-scorefetcher
      - publish-frontend
      - publish-migrations
      - publish-discordhooks
    name: deploy container
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: copy docker-compose to server
      run: |
        scp ./compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/compose.yaml
    - name: create .env file
      uses: ./.github/actions/create-env
      with:
        psql_user: ${{ secrets.PSQL_USER }}
        psql_password: ${{ secrets.PSQL_PASSWORD }}
        psql_db: ${{ secrets.PSQL_DB }}
        psql_host: ${{ secrets.PSQL_HOST }}
        psql_port: ${{ secrets.PSQL_PORT }}
        redis_password: ${{ secrets.REDIS_PASSWORD }}
        redis_user: ${{ secrets.REDIS_USER }}
        redis_user_password: ${{ secrets.REDIS_USER_PASSWORD }}
        osuapi_clientid: ${{ secrets.OSUAPI_CLIENTID }}
        osuapi_clientsecret: ${{ secrets.OSUAPI_CLIENTSECRET }}
        hooks_latestmapurl: ${{ secrets.HOOKS_SCANHOOKURL }}
        hooks_rescansurl: ${{ secrets.HOOKS_RESCANHOOKURL }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_host: ${{ secrets.SSH_HOST }}
        work_dir: ${{ secrets.WORK_DIR }}
    - name: Unlock GPG key for pass
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
    - name: Login
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "echo '${{ secrets.PAT }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin"
    - name: deploy container
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} &&
        docker compose pull && UID=$(id -u) GID=$(id -g) docker compose up -d"
    - name: Logout
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker logout ghcr.io"
    - name: Cleanup
      if: always()
      uses: ./.github/actions/cleanup-post-deploy
      with:
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_host: ${{ secrets.SSH_HOST }}
        work_dir: ${{ secrets.WORK_DIR }}
