name: Build all images and deploy

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  MIGRATIONS_IMAGE_NAME: ${{ github.actor }}/lazerboard-migrations:latest
  SCOREFETCHER_IMAGE_NAME: ${{ github.actor }}/lazerboard-scorefetcher:latest
  BACKEND_IMAGE_NAME: ${{ github.actor }}/lazerboard-backend:latest
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/lazerboard-frontend:latest

jobs:
  publish-migrations:
    name: publish migrations image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish migrations
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard.Data/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}
  publish-scorefetcher:
    needs: publish-migrations
    name: publish score fetcher image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish score fetcher
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard.ScoreFetcher/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.SCOREFETCHER_IMAGE_NAME }}
  publish-backend:
    needs: publish-migrations
    name: publish backend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
  publish-frontend:
    needs: 
      - publish-backend
      - publish-scorefetcher
    name: publish frontend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish frontend
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        file: ./Frontend/production.Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
  deploy:
    needs: publish-frontend
    name: deploy container
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: copy docker-compose to server
      run: |
        scp ./compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/compose.yaml
    - name: create prod.env file
      run: |
        touch ./prod.env
        echo "POSTGRES_USER=${{ secrets.PSQL_USER }}" >> prod.env
        echo "POSTGRES_PASSWORD=${{ secrets.PSQL_PASSWORD }}" >> prod.env
        echo "POSTGRES_DB=${{ secrets.PSQL_DB }}" >> prod.env
        echo "POSTGRES_HOST=${{ secrets.PSQL_HOST }}" >> prod.env
        echo "POSTGRES_PORT=${{ secrets.PSQL_PORT }}" >> prod.env
        echo "PGDATA=/data/postgres" >> prod.env
        echo "ASPNETCORE_ENVIRONMENT=Production" >> prod.env
        echo "Database__Database=${{ secrets.PSQL_DB }}" >> prod.env
        echo "Database__Host=db" >> prod.env
        echo "Database__Port=${{ secrets.PSQL_PORT }}" >> prod.env
        echo "Database__Username=${{ secrets.PSQL_USER }}" >> prod.env
        echo "Database__Password=${{ secrets.PSQL_PASSWORD }}" >> prod.env
        echo "OsuApi__ClientId=${{ secrets.OSUAPI_CLIENTID }}" >> prod.env
        echo "OsuApi__ClientSecret=${{ secrets.OSUAPI_CLIENTSECRET }}" >> prod.env
        echo "Caching__FileTTL=120" >> prod.env
        echo "DeleteScoresAfter=4" >> prod.env
        echo "EnableDatabaseSeeding=true" >> prod.env
        scp ./prod.env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/prod.env
    - name: Login
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ${{ secrets.PAT }} && 
        docker login ghcr.io -u ${{ github.actor }} --password-stdin"
    - name: deploy container
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} &&
        docker compose pull && docker compose up -d"
    - name: cleanup ssh
      if: always()
      run: rm -rf ~/.ssh
    - name: cleanup prod.env
      if: always()
      run: rm -f ./prod.env
