name: Publish Backend Image

on:
  push:
    branches: [ "master" ]
    paths: [ "Backend/Lazerboard/**" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/lazerboard-backend:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: copy docker-compose to server
      run: |
        scp ./compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/compose.yaml
    - name: create .env file
      uses: ./.github/actions/create-env
      with:
        psql_user: ${{ secrets.PSQL_USER }}
        psql_password: ${{ secrets.PSQL_PASSWORD }}
        psql_db: ${{ secrets.PSQL_DB }}
        psql_host: ${{ secrets.PSQL_HOST }}
        psql_port: ${{ secrets.PSQL_PORT }}
        redis_password: ${{ secrets.REDIS_PASSWORD }}
        redis_user: ${{ secrets.REDIS_USER }}
        redis_user_password: ${{ secrets.REDIS_USER_PASSWORD }}
        osuapi_clientid: ${{ secrets.OSUAPI_CLIENTID }}
        osuapi_clientsecret: ${{ secrets.OSUAPI_CLIENTSECRET }}
        hooks_scanhookurl: ${{ secrets.HOOKS_SCANHOOKURL }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_host: ${{ secrets.SSH_HOST }}
        work_dir: ${{ secrets.WORK_DIR }}
    - name: Login
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "echo '${{ secrets.PAT }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin"
    - name: deploy backend
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} &&
        docker compose pull backend && UID=$(id -u) GID=$(id -g) docker compose up -d backend"
    - name: Logout
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker logout ghcr.io"
    - name: Cleanup
      if: always()
      uses: ./.github/actions/cleanup-post-deploy
      with:
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_host: ${{ secrets.SSH_HOST }}
        work_dir: ${{ secrets.WORK_DIR }}
