name: Publish Backend Image

on:
  push:
    branches: [ "master" ]
    paths: [ "Backend/Lazerboard/**" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/lazerboard-backend:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Lazerboard/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: copy docker-compose to server
      run: |
        scp ./compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/compose.yaml
    - name: create prod.env file
      run: |
        touch ./prod.env
        echo "POSTGRES_USER=${{ secrets.PSQL_USER }}" >> prod.env
        echo "POSTGRES_PASSWORD=${{ secrets.PSQL_PASSWORD }}" >> prod.env
        echo "POSTGRES_DB=${{ secrets.PSQL_DB }}" >> prod.env
        echo "POSTGRES_HOST=${{ secrets.PSQL_HOST }}" >> prod.env
        echo "POSTGRES_PORT=${{ secrets.PSQL_PORT }}" >> prod.env
        echo "PGDATA=/data/postgres" >> prod.env
        echo "ASPNETCORE_ENVIRONMENT=Production" >> prod.env
        echo "Database__Database=${{ secrets.PSQL_DB }}" >> prod.env
        echo "Database__Host=db" >> prod.env
        echo "Database__Port=${{ secrets.PSQL_PORT }}" >> prod.env
        echo "Database__Username=${{ secrets.PSQL_USER }}" >> prod.env
        echo "Database__Password=${{ secrets.PSQL_PASSWORD }}" >> prod.env
        echo "OsuApi__ClientId=${{ secrets.OSUAPI_CLIENTID }}" >> prod.env
        echo "OsuApi__ClientSecret=${{ secrets.OSUAPI_CLIENTSECRET }}" >> prod.env
        echo "Caching__FileTTL=120" >> prod.env
        echo "DeleteScoresAfter=4" >> prod.env
        echo "EnableDatabaseSeeding=true" >> prod.env
        scp ./prod.env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/prod.env
    - name: deploy backend
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} &&
        docker compose pull backend && docker compose up -d backend"
    - name: cleanup ssh
      if: always()
      run: rm -rf ~/.ssh
    - name: cleanup prod.env
      if: always()
      run: rm -f ./prod.env
